SECRET_KEY = b'secret'

TWITTER_CLIENT_ID = ''
TWITTER_CLIENT_SECRET = ''

FACEBOOK_CLIENT_ID = ''
FACEBOOK_CLIENT_SECRET = ''

GOOGLE_CLIENT_ID = ''
GOOGLE_CLIENT_SECRET = ''

GITHUB_CLIENT_ID = ''
GITHUB_CLIENT_SECRET = ''

DROPBOX_CLIENT_ID = ''
DROPBOX_CLIENT_SECRET = ''

REDDIT_CLIENT_ID = ''
REDDIT_CLIENT_SECRET = ''

GITLAB_CLIENT_ID = ''
GITLAB_CLIENT_SECRET = ''

SLACK_CLIENT_ID = ''
SLACK_CLIENT_SECRET = ''

DISCORD_CLIENT_ID = ''
DISCORD_CLIENT_SECRET = ''

STACKOVERFLOW_CLIENT_ID = ''
STACKOVERFLOW_CLIENT_SECRET = ''
STACKOVERFLOW_CLIENT_KWARGS = {
    'api_key': '',    # required
    'api_filter': ''  # optional
}

BITBUCKET_CLIENT_ID = ''
BITBUCKET_CLIENT_SECRET = ''

STRAVA_CLIENT_ID = ''
STRAVA_CLIENT_SECRET = ''

SPOTIFY_CLIENT_ID = ''
SPOTIFY_CLIENT_SECRET = ''

YANDEX_CLIENT_ID = ''
YANDEX_CLIENT_SECRET = ''

TWITCH_CLIENT_ID = ''
TWITCH_CLIENT_SECRET = ''

VK_CLIENT_ID = ''
VK_CLIENT_SECRET = ''

BATTLENET_CLIENT_ID = ''
BATTLENET_CLIENT_SECRET = ''
