SECRET_KEY = b'secret'

TWITTER_CLIENT_ID = ''
TWITTER_CLIENT_SECRET = ''

FACEBOOK_CLIENT_ID = ''
FACEBOOK_CLIENT_SECRET = ''

GOOGLE_CLIENT_ID = ''
GOOGLE_CLIENT_SECRET = ''

GITHUB_CLIENT_ID = ''
GITHUB_CLIENT_SECRET = ''

DROPBOX_CLIENT_ID = ''
DROPBOX_CLIENT_SECRET = ''

REDDIT_CLIENT_ID = ''
REDDIT_CLIENT_SECRET = ''

GITLAB_CLIENT_ID = ''
GITLAB_CLIENT_SECRET = ''

SLACK_CLIENT_ID = ''
SLACK_CLIENT_SECRET = ''

DISCORD_CLIENT_ID = ''
DISCORD_CLIENT_SECRET = ''
